// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgK7OS6d6x0buXNJuLJwAmzfW7G3_ow5c',
    appId: '1:446728464883:web:7305650abb39a2378d0a86',
    messagingSenderId: '446728464883',
    projectId: 'meu-mengao-900c0',
    authDomain: 'meu-mengao-900c0.firebaseapp.com',
    databaseURL: 'https://meu-mengao-900c0-default-rtdb.firebaseio.com',
    storageBucket: 'meu-mengao-900c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiPdiyKhOEeEPUJk5lmWbyYK_FNFevSko',
    appId: '1:446728464883:android:2fdc9f88ed7581218d0a86',
    messagingSenderId: '446728464883',
    projectId: 'meu-mengao-900c0',
    databaseURL: 'https://meu-mengao-900c0-default-rtdb.firebaseio.com',
    storageBucket: 'meu-mengao-900c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiBHfOxTd3UIAgB97UPBLHVVH6c4xIaU8',
    appId: '1:446728464883:ios:a9e53dfd860f18c78d0a86',
    messagingSenderId: '446728464883',
    projectId: 'meu-mengao-900c0',
    databaseURL: 'https://meu-mengao-900c0-default-rtdb.firebaseio.com',
    storageBucket: 'meu-mengao-900c0.appspot.com',
    iosClientId: '446728464883-os5ughvjeqkneefsp0sadus9sau7flhg.apps.googleusercontent.com',
    iosBundleId: 'xyz.joaopegoraro.meuMengao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiBHfOxTd3UIAgB97UPBLHVVH6c4xIaU8',
    appId: '1:446728464883:ios:2c4fb97c6765a90e8d0a86',
    messagingSenderId: '446728464883',
    projectId: 'meu-mengao-900c0',
    databaseURL: 'https://meu-mengao-900c0-default-rtdb.firebaseio.com',
    storageBucket: 'meu-mengao-900c0.appspot.com',
    iosClientId: '446728464883-8im2u80pafrvf870qvgcn2m74n1pg0co.apps.googleusercontent.com',
    iosBundleId: 'xyz.joaopegoraro.meuMengao.RunnerTests',
  );
}
